apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-cheetah-config
data:
  CHEETAH_CONFIG: {{ .Values.cheetah.config | quote }}
  CHEETAH_PIPELINE: {{ .Values.cheetah.pipeline | quote }}
  CHEETAH_SOURCE: {{ .Values.cheetah.source | quote }}
  CHEETAH_LOGLEVEL: {{ .Values.cheetah.loglevel | quote }}
